# Generated by Django 3.1 on 2020-08-25 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boxs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumberBox', models.PositiveIntegerField()),
                ('Password', models.CharField(max_length=50)),
                ('OnRent', models.BooleanField(default=False)),
                ('DoorBox', models.BooleanField(default=False)),
                ('IdLocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lockers')),
            ],
        ),
    ]
