# Generated by Django 3.1 on 2020-08-25 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_boxs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxs',
            name='IdLocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxs', to='api.lockers'),
        ),
    ]
