# Generated by Django 3.1 on 2020-08-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200825_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boxs',
            options={'ordering': ['NumberBox']},
        ),
    ]
