# Generated by Django 3.1 on 2020-08-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200825_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lockers',
            options={'ordering': ['IdLocker']},
        ),
    ]
